FORMAT: 1A
HOST: http://api.tidepool.io

# Tidepool Armada
**Armada is an aquatic term for a group of something (in this case, warships). Armada stores and manipulates groups of users for managing permissions and messages.**

## Overview

Armada stores and manipulates groups of users for managing permissions and messages.


# Group Group

## Health Check [/status]
### Retrieve status information [GET]
Returns a status health check with a list of status of its dependencies. 
If the server is operating properly and all dependencies are up and 
running, returns 200, otherwise 500. In either case, the body contains a 
list of up and down dependencies.


+ Response 200

        {
            "up" : [ "mongo" ],
            "down" : []
        }
    
+ Response 500

        If the server is *not* operating properly and one or more dependencies
        have failed to start or are no longer running.

        {
            "up" : [],
            "down" : [ "mongo" ]
        }

## User Membership [/membership/{userid}/member]
### Fetch group membership information [GET]
Returns the groups that the given userID is a member of. If found, returns
an object containing an array of groups. If there are no groups, the response 
is a 204 (rather than an empty array). 

+ Request

    + Headers
    
            x-tidepool-session-token : 23sadf87.123840.aasd90JKj
            

+ Response 200

        {
            groups: [ "12a34f5", "13bdc814" ]
        }
        
+ Response 204

+ Response 400

## Managing groups [/]
### Create a group [POST]
Creates a new group object and returns its ID.

+ Request

    + Headers
    
            x-tidepool-session-token : 23sadf87.123840.aasd90JKj
            
    + Body
        
            {
                "members": ["99999", "222222", "33333212"]
            }

+ Response 201

        {
            id: "12a34f5"
        }
        
+ Response 400


## Managing group members [/{groupid}/user]
### Add a user to a group [POST]
Puts the identified user into a group.

+ Request

    + Headers
    
            x-tidepool-session-token : 23sadf87.123840.aasd90JKj
            
    + Body
        
            {
                "userid": "12363523"
            }

+ Response 200

        {
            id: "12a34f5"
        }
        
+ Response 204

+ Response 400



